### ISSUE TITLE
Wowza heap

### ISSUE THREAD

**Issue by Tkamiya** [WowzaMediaSystems/wse-example-pushpublish-hls#10]
Hello,

I found an issue of Wowza heap increasing with this HLS output.
When I started the HLS output, then the Wowza heap was just 10%.
But now, the Wowza heap is about 90% and the Wowza was stopped by the Wowza heap increasing.

I tried with the following AWS instance.

r3.xlarge

The instance has 30GB RAM but the Wowza has been stopped by Wowza heap issue.

Would you check this case?

Best regards,

Taka

**Comment by rogerlittin** [comment]
Hi,

What version of Wowza Streaming Engine are you using? There was an issue, like what you are describing, with earlier versions if you set the cupertino.chunkcount to a very high or infinite value. There was a memory leak that occurred fairly quickly, due to the chunk data not being released. This has now been resolved however due to the fact that the chunks must still be available to build the manifest, I guess if the server is running for long enough (months), pushing the same stream then it may be possible that it could run low on memory. The only option in this case would be to cycle the server every so often.

**Comment by Tkamiya** [comment]
Hi,

I'm using 4.7.7. I think it is current latest version of the Wowza Streaming Engine.
Currently, I'm using server restart function to release the Wowza heap.

**Comment by rogerlittin** [comment]
Hi,

How long does it take for the heap to fill up?

Next time it happens, please capture a heap dump and then zip it up, along with the log files since the last restart and the conf folder and then submit a support ticket so we can investigate.

Thanks,

Roger.

**Comment by Tkamiya** [comment]
Hi Roger,

It will take about 2 hours later when I use 8Mbps as bitrate.

Would you tell me, how do I dump the heap?
I'm using a Windows environment.

Best regards,

Taka

**Comment by Tkamiya** [comment]
Hi Roger,

I understood how do I get the Wowza heap.
I will provide it after downloaded the heap file from WowzaStreamingEngine.

Best regards,

Taka

**Comment by Tkamiya** [comment]
I have uploaded the heap file and log, conf folders in my storage.
Would you check the following link?
I have created the support ticket in Wowza forum.
https://www.wowza.com/community/questions/49864/view.html

**Comment by rogerlittin** [comment]
Hi,

Can you please log into the Wowza portal and open a ticket there. This way, we will be able to assist privately, instead of in the public forum.

https://store.wowza.com/portal/help/engine

Thanks,

Roger.
